server:
  port: 9003

spring:
  application:
    name: comment-service
#  cloud:
#    nacos:
#      server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog_cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 032581
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

mybatis:
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    enabled: true

# Feign服务地址配置（可通过环境变量覆盖）
feign:
  user-service:
    url: http://localhost:9011
  article-service:
    url: http://localhost:9020