version: '3.8'

services:
  redis:
    image: redis:7
    container_name: blog-redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: blog-rabbitmq
    ports:
      - "35672:5672"
      - "15672:15672"

  nacos:
    image: nacos/nacos-server:v2.3.2
    container_name: blog-nacos
    environment:
      MODE: standalone
      PREFER_HOST_MODE: hostname
    ports:
      - "8848:8848"

  k6:
    image: grafana/k6:latest
    container_name: blog-k6
    profiles:
      - tools
    working_dir: /scripts
    volumes:
      - ./pressure-test:/scripts
    extra_hosts:
      - "host.docker.internal:host-gateway"
    entrypoint:
      - k6
