server:
  port: 8084

spring:
  cloud:
    sentinel:
      enabled: ${SENTINEL_ENABLED:true}
      transport:
        dashboard: ${SENTINEL_DASHBOARD:sentinel-dashboard:8858}
        port: ${SENTINEL_TRANSPORT_PORT:8719}
      eager: true
      filter:
        enabled: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    enabled: true

logging:
  level:
    com.notifyservice: info

