server:
  port: 9004

spring:
  application:
    name: notify-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/blog_cloud?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 032581
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest

mybatis:
  configuration:
    map-underscore-to-camel-case: true