server:
  port: 8080

spring:
  application:
    name: blog-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: user-service
          uri: ${gateway.routes.user-service-uri:http://127.0.0.1:9011}
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

        - id: article-service
          uri: ${gateway.routes.article-service-uri:http://127.0.0.1:9020}
          predicates:
            - Path=/api/article/**
          filters:
            - StripPrefix=1

        - id: comment-service
          uri: ${gateway.routes.comment-service-uri:http://127.0.0.1:9003}
          predicates:
            - Path=/api/comment/**
          filters:
            - StripPrefix=1

        - id: notify-service
          uri: ${gateway.routes.notify-service-uri:http://127.0.0.1:9004}
          predicates:
            - Path=/api/notify/**
          filters:
            - StripPrefix=1

  data:
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}

logging:
  level:
    org.springframework.cloud.gateway: info
    com.bloggateway: info
