spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1

        - id: article-service
          uri: lb://article-service
          predicates:
            - Path=/api/article/**
          filters:
            - StripPrefix=1

        - id: comment-service
          uri: lb://comment-service
          predicates:
            - Path=/api/comment/**
          filters:
            - StripPrefix=1

        - id: notify-service
          uri: lb://notify-service
          predicates:
            - Path=/api/notify/**
          filters:
            - StripPrefix=1
