param(
    [string]$OutputPath = ".env.production.local",
    [switch]$Force
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

function New-Base64Secret {
    param([int]$Length = 32)

    $buffer = [Array]::CreateInstance([byte], $Length)
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $rng.GetBytes($buffer)
    } finally {
        $rng.Dispose()
    }
    return [Convert]::ToBase64String($buffer)
}

function New-Password {
    param([int]$Length = 24)

    $secret = New-Base64Secret -Length $Length
    return $secret.TrimEnd("=").Replace("+", "A").Replace("/", "B")
}

if ([System.IO.Path]::IsPathRooted($OutputPath)) {
    $resolvedOutput = [System.IO.Path]::GetFullPath($OutputPath)
} else {
    $resolvedOutput = [System.IO.Path]::GetFullPath((Join-Path (Get-Location) $OutputPath))
}
if ((Test-Path -LiteralPath $resolvedOutput) -and -not $Force) {
    throw "Output file already exists: $resolvedOutput. Re-run with -Force if you intend to replace it."
}

$values = [ordered]@{
    "COMPOSE_PROJECT_NAME"       = "blog-cloud"
    "TZ"                         = "Asia/Shanghai"
    "MYSQL_ROOT_PASSWORD"        = New-Password -Length 24
    "MYSQL_DATABASE"             = "blog_cloud"
    "MYSQL_APP_USERNAME"         = "blog_cloud"
    "MYSQL_APP_PASSWORD"         = New-Password -Length 24
    "REDIS_PASSWORD"             = New-Password -Length 24
    "RABBITMQ_DEFAULT_USER"      = "blog_cloud"
    "RABBITMQ_DEFAULT_PASS"      = New-Password -Length 24
    "NACOS_USERNAME"             = "nacos"
    "NACOS_PASSWORD"             = New-Password -Length 24
    "NACOS_AUTH_ENABLE"          = "true"
    "NACOS_AUTH_IDENTITY_KEY"    = New-Password -Length 12
    "NACOS_AUTH_IDENTITY_VALUE"  = New-Password -Length 24
    "NACOS_AUTH_TOKEN"           = New-Base64Secret -Length 48
    "JWT_SECRET"                 = New-Base64Secret -Length 48
    "AUTH_COOKIE_SECURE"         = "true"
    "AUTH_COOKIE_SAME_SITE"      = "Lax"
}

$lines = @(
    "# Generated by deploy/scripts/generate-secrets.ps1"
    "# Do not commit this file. Rotate values per environment and store them in the deployment secret manager."
)

foreach ($entry in $values.GetEnumerator()) {
    $lines += "$($entry.Key)=$($entry.Value)"
}

New-Item -ItemType Directory -Path ([System.IO.Path]::GetDirectoryName($resolvedOutput)) -Force | Out-Null
Set-Content -LiteralPath $resolvedOutput -Value $lines -Encoding UTF8
Write-Output "Generated secret environment file: $resolvedOutput"
